framework:
    messenger:
        failure_transport: failed

        transports:
            sync: 'sync://'
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: failed
                    queues:
                        failed: ~
            default:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: default
                    queues:
                        default: ~

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: default
            Symfony\Component\Notifier\Message\ChatMessage: default
            Symfony\Component\Notifier\Message\SmsMessage: default

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
