version: '3.7'

services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: dev
    links:
      - db
    volumes: &volumes
      - ./:/var/www

  builder:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: main
    working_dir: /var/www
    command: composer install
    restart: 'no'
    volumes: *volumes

  nginx:
    build: docker/nginx
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes: *volumes

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: linux1
      POSTGRES_DB: testdb
      POSTGRES_ROOT_PASSWORD: linux1
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
        driver: local